### ISSUE TITLE
Error loading dependencies

### ISSUE THREAD

**Issue by sorianocom** [EL-BID/URSA#10]
Ejecuto el docker sin problemas pero al abrir el navegador en http://localhost:8050 queda en blanco con la leyenda: 
Error loading dependencies

Alguna pista que puede ser el error?

Adjunto la captura de la consola al ejecturar:
---------
Successfully saved authorization token.
¡La autenticación de Google Earth Engine ha sido exitosa!
Dash is running on http://0.0.0.0:8050/

 * Serving Flask app 'app'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://172.17.0.2:8050
Press CTRL+C to quit
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /assets/main.css?m=1708453196.0 HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/deps/polyfill@7.v2_16_0m1709359684.12.1.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /assets/bootstrap.min.css?m=1708453196.0 HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/deps/react@16.v2_16_0m1709359684.14.0.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_16_0m1709359684.14.0.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_16_0m1709359683.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_16_0m1709359684.8.1.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_13_1m1709359684.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/html/dash_html_components.v2_0_17m1709359684.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash/dash_table/bundle.v5_2_10m1709359683.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-layout HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-dependencies HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /assets/favicon.ico?m=1708453196.0 HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "POST /_dash-dist HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:14:17] "GET /_dash-component-suites/dash_bootstrap_components/_components/dash_bootstrap_components.v1_5_0m1694087134.min.js HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:16:59] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:16:59] "GET /assets/bootstrap.min.css?m=1708453196.0 HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:16:59] "GET /assets/main.css?m=1708453196.0 HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:16:59] "GET /_dash-layout HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:16:59] "GET /_dash-dependencies HTTP/1.1" 200 -
172.17.0.1 - - [08/Mar/2024 18:16:59] "POST /_dash-dist HTTP/1.1" 200 -

**Comment by bitsandbricks** [comment]
Gracias por el aviso -logramos reproducir el problema, ya estamos trabajando en un fix

**Comment by bitsandbricks** [comment]
Hola @sorianocom, intentalo ahora :)

**Comment by sorianocom** [comment]
Funciona! :) Muchas gracias por la pronta respuesta @bitsandbricks y @RodolfoFigueroa. Un gran abrazo!
