### ISSUE TITLE
Error in coastal cities [Peru]

### ISSUE THREAD

**Issue by amrcode1** [EL-BID/URSA#9]
Hello everyone, it happens to me that when I try to generate the heat island map for any coastal city in my country, it is not possible. With any other non-coastal city I can get the heat island map.

The cities that I tested several times to rule out any other cause are the following: Chiclayo, Chimbote, Chincha Alta, Huacho, Lima.

The following error message is thrown in the console:

> Generating temperature discrete image ...
> [2024-02-17 01:24:31,414] ERROR in app: Exception on /_dash-update-component [POST]
> Traceback (most recent call last):
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/dash/dash.py", line 1310, in dispatch
>     ctx.run(
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/dash/_callback.py", line 442, in add_context
>     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
>   File "/app/pages/suhi.py", line 522, in update_mitigation_kilometers
>     urban_mean_temp = ht.get_urban_mean(bbox_latlon, "Qall", 2022, path_cache)
>   File "/app/src/ursa/heat_islands.py", line 611, in get_urban_mean
>     temps = load_or_get_temps(bbox_ee, start_date, end_date, path_cache, reducer)
>   File "/app/src/ursa/heat_islands.py", line 158, in load_or_get_temps
>     temps = get_temps(lst, masks, path_cache)
>   File "/app/src/ursa/heat_islands.py", line 136, in get_temps
>     t_dict["rural_old"]["mean"] = rural_mean
> KeyError: 'rural_old'
> 172.17.0.1 - - [17/Feb/2024 01:24:31] "POST /_dash-update-component HTTP/1.1" 500 -
> [2024-02-17 01:24:34,831] ERROR in app: Exception on /_dash-update-component [POST]
> Traceback (most recent call last):
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/dash/dash.py", line 1310, in dispatch
>     ctx.run(
>   File "/opt/conda/envs/ursa/lib/python3.10/site-packages/dash/_callback.py", line 442, in add_context
>     output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
>   File "/app/pages/suhi.py", line 660, in generate_maps
>     radial_temp_plot = ht.plot_radial_temperature(
>   File "/app/src/ursa/heat_islands.py", line 502, in plot_radial_temperature
>     df = load_or_get_radial_f(
>   File "/app/src/ursa/heat_islands.py", line 491, in load_or_get_radial_f
>     img_suhi = get_suhi(bbox_ee, start_date, end_date, path_cache)
>   File "/app/src/ursa/heat_islands.py", line 170, in get_suhi
>     temps = load_or_get_temps(bbox_ee, start_date, end_date, path_cache, reducer)
>   File "/app/src/ursa/heat_islands.py", line 158, in load_or_get_temps
>     temps = get_temps(lst, masks, path_cache)
>   File "/app/src/ursa/heat_islands.py", line 136, in get_temps
>     t_dict["rural_old"]["mean"] = rural_mean
> KeyError: 'rural_old'

Any guidance on how to resolve it? The tool is great and I would like to try it better.
Thanks in advance.

OS: Windows 11 with Docker 4.25.1 (128006).

**Comment by bitsandbricks** [comment]
Hi there! The issue has been solved - please try the latest version, heat island maps for coastal cities should render fine now.

**Comment by bitsandbricks** [comment]
Solved
